Repository eusouorui/Deletos, pull requests merged in 2022-12, with the labels that each got.

#5 Feature/4 create documentation
  Documentation/Setup.md
  Documentation/Setup2.md
  README.md
Labels: Documentation

#7 Fixed documentation URLs
  Documentation/Setup.md
  Documentation/Setup2.md
Labels: Bug, Documentation

#10 Code cleanup
  Documentation/Setup.md
  Profiles/Rui.cs
  Program.cs
  README.md
  Strings/ForVsForEach.cs
Labels: Enhancement

#9 Feature/exit
  Handlers/ProgramHandler.cs
Labels: Bug, Enhancement

#11 Added features for Rui's Menu
  Profiles/Rui.cs
Labels: Enhancement
